name: edamameBank
version: '${project.version}'
main: com.edamame.edamamebank.EdamameBank
api-version: '1.20'

commands:
  bankcreate:
    description: description
    permission: edamameBank.bankcreate

  addmoney:
    description: description
    permission: edamameBank.addmoney

  bank:
    description: description
    permission: edamameBank.bank

  pay:
    description: description
    permission: edamameBank.pay

  atm:
    description: description
    permission: edamameBank.atm