name: edamameBank
version: '1.0-SNAPSHOT'
main: com.edamame.edamamebank.EdamameBank
api-version: '1.20'

commands:
  bankcreate:
    description: description

  addmoney:
    description: description

  bank:
    description: description

  pay:
    description: description